// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraSuaApp.Infrastructure.Data;

#nullable disable

namespace TraSuaApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250718095617_SeedNhomSanPhamSTT2")]
    partial class SeedNhomSanPhamSTT2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToppingNhomSanPham", b =>
                {
                    b.Property<Guid>("IdTopping")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhomSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdTopping", "IdNhomSanPham")
                        .HasName("PK_ToppingNhomSanPham");

                    b.HasIndex("IdNhomSanPham");

                    b.ToTable("ToppingNhomSanPhams", (string)null);
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamBienThe")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SanPhamBienTheId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TichDiem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HoaDonId" }, "IX_ChiTietHoaDons_HoaDonId");

                    b.HasIndex(new[] { "SanPhamBienTheId" }, "IX_ChiTietHoaDons_SanPhamBienTheId");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonNhap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("HoaDonNhapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDonNhap")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNguyenLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NguyenLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HoaDonNhapId" }, "IX_ChiTietHoaDonNhaps_HoaDonNhapId");

                    b.HasIndex(new[] { "NguyenLieuId" }, "IX_ChiTietHoaDonNhaps_NguyenLieuId");

                    b.ToTable("ChiTietHoaDonNhaps");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonTopping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTopping")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<Guid>("ToppingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HoaDonId" }, "IX_ChiTietHoaDonToppings_HoaDonId");

                    b.HasIndex(new[] { "ToppingId" }, "IX_ChiTietHoaDonToppings_ToppingId");

                    b.ToTable("ChiTietHoaDonToppings");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietTuyChinhMon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdTuyChinhMon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TuyChinhMonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TuyChinhMonId" }, "IX_ChiTietTuyChinhMons_TuyChinhMonId");

                    b.ToTable("ChiTietTuyChinhMons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CongThuc", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamBienThe")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SanPhamBienTheId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SanPhamBienTheId" }, "IX_CongThucs_SanPhamBienTheId");

                    b.ToTable("CongThucs");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CongViecNoiBo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaHoanThanh")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdNguoiTao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguoiTaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NguoiTaoId" }, "IX_CongViecNoiBos_NguoiTaoId");

                    b.ToTable("CongViecNoiBos");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CustomerPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TongDiem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "KhachHangId" }, "IX_CustomerPoints_KhachHangId");

                    b.ToTable("CustomerPoints");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CustomerPointLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DiemThayDoi")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "KhachHangId" }, "IX_CustomerPointLogs_KhachHangId");

                    b.ToTable("CustomerPointLogs");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid?>("IdBan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNhomHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdTaiKhoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TaiKhoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "KhachHangId" }, "IX_HoaDons_KhachHangId");

                    b.HasIndex(new[] { "TaiKhoanId" }, "IX_HoaDons_TaiKhoanId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDonNhap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdTaiKhoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TaiKhoanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TaiKhoanId" }, "IX_HoaDonNhaps_TaiKhoanId");

                    b.ToTable("HoaDonNhaps");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DuocNhanVoucher")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OldId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHangAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK_ShippingAddresses");

                    b.HasIndex(new[] { "IdKhachHang" }, "IX_ShippingAddresses_KhachHangId");

                    b.ToTable("KhachHangAddresses");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHangPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_CustomerPhoneNumbers");

                    b.HasIndex(new[] { "IdKhachHang" }, "IX_CustomerPhoneNumbers_KhachHangId");

                    b.ToTable("KhachHangPhones");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.LichSuChinhSua", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdTaiKhoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoaiThaoTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TaiKhoanId" }, "IX_LichSuChinhSuas_TaiKhoanId");

                    b.ToTable("LichSuChinhSuas");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.LichSuNhapXuatKho", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdNguyenLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NguyenLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NguyenLieuId" }, "IX_LichSuNhapXuatKhos_NguyenLieuId");

                    b.ToTable("LichSuNhapXuatKhos");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ip")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IP");

                    b.Property<string>("Method")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequestBodyShort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseBodyShort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Logs__3214EC07710A63D8");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.NguyenLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TonKho")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("NguyenLieus");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.NhomSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__NhomSanP__3214EC07C10A2B21");

                    b.HasIndex(new[] { "Ten" }, "IX_NhomSanPham_Ten")
                        .IsUnique();

                    b.ToTable("NhomSanPhams");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.NoHoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayGhiNhan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienDaTra")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SoTienNo")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HoaDonId" }, "IX_NoHoaDons_HoaDonId");

                    b.ToTable("NoHoaDons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPaymentMethod")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdTaiKhoanThucHien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid?>("TaiKhoanThucHienId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HoaDonId" }, "IX_Payments_HoaDonId");

                    b.HasIndex(new[] { "PaymentMethodId" }, "IX_Payments_PaymentMethodId");

                    b.HasIndex(new[] { "TaiKhoanThucHienId" }, "IX_Payments_TaiKhoanThucHienId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DaBan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DinhLuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdNhomSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdOld")
                        .HasColumnType("int")
                        .HasColumnName("IdOLD");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NgungBan")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TichDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VietTat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdNhomSanPham");

                    b.HasIndex(new[] { "Ten" }, "IX_SanPham_Ten")
                        .IsUnique();

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPhamBienThe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("MacDinh")
                        .HasColumnType("bit");

                    b.Property<Guid>("SanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenBienThe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdSanPham" }, "IX_BienThe_MacDinh")
                        .IsUnique()
                        .HasFilter("([MacDinh]=(1))");

                    b.HasIndex(new[] { "TenBienThe", "IdSanPham" }, "IX_BienThe_Ten_IdSanPham")
                        .IsUnique();

                    b.HasIndex(new[] { "SanPhamId" }, "IX_SanPhamBienThes_SanPhamId");

                    b.ToTable("SanPhamBienThes");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SuDungNguyenLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongThucId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCongThuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNguyenLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NguyenLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CongThucId" }, "IX_SuDungNguyenLieus_CongThucId");

                    b.HasIndex(new[] { "NguyenLieuId" }, "IX_SuDungNguyenLieus_NguyenLieuId");

                    b.ToTable("SuDungNguyenLieus");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenHienThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaiTro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenDangNhap" }, "IX_TaiKhoan_TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Topping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NgungBan")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ten" }, "IX_Topping_Ten")
                        .IsUnique();

                    b.ToTable("Toppings");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.TuyChinhMon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ChoPhepChonNhieuGiaTri")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TuyChinhMons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.VoucherLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaTriApDung")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdVoucher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HoaDonId" }, "IX_VoucherLogs_HoaDonId");

                    b.HasIndex(new[] { "VoucherId" }, "IX_VoucherLogs_VoucherId");

                    b.ToTable("VoucherLogs");
                });

            modelBuilder.Entity("ToppingNhomSanPham", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.NhomSanPham", null)
                        .WithMany()
                        .HasForeignKey("IdNhomSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ToppingNhomSanPham_NhomSanPham");

                    b.HasOne("TraSuaApp.Domain.Entities.Topping", null)
                        .WithMany()
                        .HasForeignKey("IdTopping")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ToppingNhomSanPham_Topping");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.SanPhamBienThe", "SanPhamBienThe")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("SanPhamBienTheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamBienThe");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonNhap", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDonNhap", "HoaDonNhap")
                        .WithMany("ChiTietHoaDonNhaps")
                        .HasForeignKey("HoaDonNhapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("ChiTietHoaDonNhaps")
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDonNhap");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonTopping", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDonToppings")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.Topping", "Topping")
                        .WithMany("ChiTietHoaDonToppings")
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietTuyChinhMon", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.TuyChinhMon", "TuyChinhMon")
                        .WithMany("ChiTietTuyChinhMons")
                        .HasForeignKey("TuyChinhMonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TuyChinhMon");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CongThuc", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.SanPhamBienThe", "SanPhamBienThe")
                        .WithMany("CongThucs")
                        .HasForeignKey("SanPhamBienTheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPhamBienThe");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CongViecNoiBo", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.TaiKhoan", "NguoiTao")
                        .WithMany("CongViecNoiBos")
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CustomerPoint", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany("CustomerPoints")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CustomerPointLog", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany("CustomerPointLogs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDon", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangId");

                    b.HasOne("TraSuaApp.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("HoaDons")
                        .HasForeignKey("TaiKhoanId");

                    b.Navigation("KhachHang");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDonNhap", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("HoaDonNhaps")
                        .HasForeignKey("TaiKhoanId");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHangAddress", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany("KhachHangAddresses")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShippingAddresses_KhachHangs_KhachHangId");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHangPhone", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany("KhachHangPhones")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CustomerPhoneNumbers_KhachHangs_KhachHangId");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.LichSuChinhSua", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("LichSuChinhSuas")
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.LichSuNhapXuatKho", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("LichSuNhapXuatKhos")
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.NoHoaDon", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("NoHoaDons")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Payment", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("Payments")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.TaiKhoan", "TaiKhoanThucHien")
                        .WithMany("Payments")
                        .HasForeignKey("TaiKhoanThucHienId");

                    b.Navigation("HoaDon");

                    b.Navigation("PaymentMethod");

                    b.Navigation("TaiKhoanThucHien");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPham", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.NhomSanPham", "IdNhomSanPhamNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdNhomSanPham")
                        .HasConstraintName("FK_SanPhams_NhomSanPhams");

                    b.Navigation("IdNhomSanPhamNavigation");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPhamBienThe", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.SanPham", "SanPham")
                        .WithMany("SanPhamBienThes")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SuDungNguyenLieu", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.CongThuc", "CongThuc")
                        .WithMany("SuDungNguyenLieus")
                        .HasForeignKey("CongThucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("SuDungNguyenLieus")
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongThuc");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.VoucherLog", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("VoucherLogs")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.Voucher", "Voucher")
                        .WithMany("VoucherLogs")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CongThuc", b =>
                {
                    b.Navigation("SuDungNguyenLieus");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDonToppings");

                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("NoHoaDons");

                    b.Navigation("Payments");

                    b.Navigation("VoucherLogs");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDonNhap", b =>
                {
                    b.Navigation("ChiTietHoaDonNhaps");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHang", b =>
                {
                    b.Navigation("CustomerPointLogs");

                    b.Navigation("CustomerPoints");

                    b.Navigation("HoaDons");

                    b.Navigation("KhachHangAddresses");

                    b.Navigation("KhachHangPhones");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.NguyenLieu", b =>
                {
                    b.Navigation("ChiTietHoaDonNhaps");

                    b.Navigation("LichSuNhapXuatKhos");

                    b.Navigation("SuDungNguyenLieus");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.NhomSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPham", b =>
                {
                    b.Navigation("SanPhamBienThes");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPhamBienThe", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("CongThucs");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.TaiKhoan", b =>
                {
                    b.Navigation("CongViecNoiBos");

                    b.Navigation("HoaDonNhaps");

                    b.Navigation("HoaDons");

                    b.Navigation("LichSuChinhSuas");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Topping", b =>
                {
                    b.Navigation("ChiTietHoaDonToppings");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.TuyChinhMon", b =>
                {
                    b.Navigation("ChiTietTuyChinhMons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Voucher", b =>
                {
                    b.Navigation("VoucherLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
