// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraSuaApp.Infrastructure.Data;

#nullable disable

namespace TraSuaApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250701052654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamBienThe")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SanPhamBienTheId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TichDiem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("SanPhamBienTheId");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonNhap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HoaDonNhapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDonNhap")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNguyenLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NguyenLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonNhapId");

                    b.HasIndex("NguyenLieuId");

                    b.ToTable("ChiTietHoaDonNhaps");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonTopping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTopping")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<Guid>("ToppingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("ToppingId");

                    b.ToTable("ChiTietHoaDonToppings");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietTuyChinhMon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdTuyChinhMon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TuyChinhMonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TuyChinhMonId");

                    b.ToTable("ChiTietTuyChinhMons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CongThuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamBienThe")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SanPhamBienTheId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamBienTheId");

                    b.ToTable("CongThucs");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CongViecNoiBo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaHoanThanh")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdNguoiTao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguoiTaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("CongViecNoiBos");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CustomerPhoneNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.ToTable("CustomerPhoneNumbers");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CustomerPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TongDiem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.ToTable("CustomerPoints");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CustomerPointLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DiemThayDoi")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.ToTable("CustomerPointLogs");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("IdBan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNhomHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdTaiKhoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TaiKhoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDonNhap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdTaiKhoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TaiKhoanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("HoaDonNhaps");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DuocNhanVoucher")
                        .HasColumnType("bit");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.LichSuChinhSua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdTaiKhoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoaiThaoTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("LichSuChinhSuas");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.LichSuNhapXuatKho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdNguyenLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NguyenLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguyenLieuId");

                    b.ToTable("LichSuNhapXuatKhos");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.NguyenLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TonKho")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("NguyenLieus");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.NoHoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayGhiNhan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienDaTra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienNo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.ToTable("NoHoaDons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPaymentMethod")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdTaiKhoanThucHien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("TaiKhoanThucHienId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("TaiKhoanThucHienId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DaBan")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdNhomSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VietTat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPhamBienThe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenBienThe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamId");

                    b.ToTable("SanPhamBienThes");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ShippingAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.ToTable("ShippingAddresses");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SuDungNguyenLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongThucId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCongThuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNguyenLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NguyenLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CongThucId");

                    b.HasIndex("NguyenLieuId");

                    b.ToTable("SuDungNguyenLieus");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Topping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Toppings");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.TuyChinhMon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ChoPhepChonNhieuGiaTri")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TuyChinhMons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.VoucherLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaTriApDung")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdVoucher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("VoucherId");

                    b.ToTable("VoucherLogs");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.SanPhamBienThe", "SanPhamBienThe")
                        .WithMany()
                        .HasForeignKey("SanPhamBienTheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamBienThe");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonNhap", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDonNhap", "HoaDonNhap")
                        .WithMany("ChiTietHoaDonNhaps")
                        .HasForeignKey("HoaDonNhapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("LichSuNhap")
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDonNhap");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonTopping", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietToppings")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.Topping", "Topping")
                        .WithMany("ChiTietHoaDonToppings")
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietTuyChinhMon", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.TuyChinhMon", "TuyChinhMon")
                        .WithMany("ChiTietTuyChinhMons")
                        .HasForeignKey("TuyChinhMonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TuyChinhMon");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CongThuc", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.SanPhamBienThe", "SanPhamBienThe")
                        .WithMany()
                        .HasForeignKey("SanPhamBienTheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPhamBienThe");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CongViecNoiBo", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.TaiKhoan", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CustomerPhoneNumber", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CustomerPoint", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CustomerPointLog", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDon", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId");

                    b.HasOne("TraSuaApp.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId");

                    b.Navigation("KhachHang");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDonNhap", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.LichSuChinhSua", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.LichSuNhapXuatKho", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.NoHoaDon", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Payment", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("Payments")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.TaiKhoan", "TaiKhoanThucHien")
                        .WithMany()
                        .HasForeignKey("TaiKhoanThucHienId");

                    b.Navigation("HoaDon");

                    b.Navigation("PaymentMethod");

                    b.Navigation("TaiKhoanThucHien");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPhamBienThe", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.SanPham", "SanPham")
                        .WithMany("BienThe")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ShippingAddress", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany("ShippingAddresses")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SuDungNguyenLieu", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.CongThuc", "CongThuc")
                        .WithMany("SuDungNguyenLieus")
                        .HasForeignKey("CongThucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("SuDungNguyenLieus")
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongThuc");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.VoucherLog", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.Voucher", "Voucher")
                        .WithMany("VoucherLogs")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CongThuc", b =>
                {
                    b.Navigation("SuDungNguyenLieus");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("ChiTietToppings");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDonNhap", b =>
                {
                    b.Navigation("ChiTietHoaDonNhaps");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHang", b =>
                {
                    b.Navigation("PhoneNumbers");

                    b.Navigation("ShippingAddresses");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.NguyenLieu", b =>
                {
                    b.Navigation("LichSuNhap");

                    b.Navigation("SuDungNguyenLieus");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPham", b =>
                {
                    b.Navigation("BienThe");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Topping", b =>
                {
                    b.Navigation("ChiTietHoaDonToppings");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.TuyChinhMon", b =>
                {
                    b.Navigation("ChiTietTuyChinhMons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Voucher", b =>
                {
                    b.Navigation("VoucherLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
