// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraSuaApp.Infrastructure;

#nullable disable

namespace TraSuaApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250912064913_AddNgayCanhBao_XNgayCanhBao_T")]
    partial class AddNgayCanhBao_XNgayCanhBao_T
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChiTieuHangNgay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BillThang")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguyenLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NguyenLieuId");

                    b.ToTable("ChiTieuHangNgays");
                });

            modelBuilder.Entity("ToppingNhomSanPhamLink", b =>
                {
                    b.Property<Guid>("ToppingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ToppingID");

                    b.Property<Guid>("NhomSanPhamId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NhomSanPhamID");

                    b.HasKey("ToppingId", "NhomSanPhamId");

                    b.HasIndex("NhomSanPhamId");

                    b.ToTable("ToppingNhomSanPhamLinks", (string)null);
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteText")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int>("OldId")
                        .HasColumnType("int");

                    b.Property<Guid>("SanPhamBienTheId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenBienThe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ToppingText")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HoaDonId" }, "IX_ChiTietHoaDons_HoaDonId");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_ChiTietHoaDons_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "SanPhamBienTheId" }, "IX_ChiTietHoaDons_SanPhamBienTheId");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonNhapEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("HoaDonNhapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguyenLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HoaDonNhapId" }, "IX_ChiTietHoaDonNhaps_HoaDonNhapId");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_ChiTietHoaDonNhaps_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "NguyenLieuId" }, "IX_ChiTietHoaDonNhaps_NguyenLieuId");

                    b.ToTable("ChiTietHoaDonNhaps");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonNo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienNo")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK_NoHoaDons");

                    b.HasIndex("KhachHangId");

                    b.HasIndex(new[] { "HoaDonId" }, "IX_NoHoaDons_HoaDonId");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_NoHoaDons_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.ToTable("ChiTietHoaDonNos");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiemThayDoi")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_CustomerPointLogs");

                    b.HasIndex("HoaDonId");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_ChiTietHoaDonPoints_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "KhachHangId" }, "IX_CustomerPointLogs_KhachHangId");

                    b.ToTable("ChiTietHoaDonPoints");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChiTietHoaDonNoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaiThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PhuongThucThanhToanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenPhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Payments");

                    b.HasIndex("ChiTietHoaDonNoId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex(new[] { "HoaDonId" }, "IX_Payments_HoaDonId");

                    b.HasIndex(new[] { "PhuongThucThanhToanId" }, "IX_Payments_PaymentMethodId");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_ThanhToans_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.ToTable("ChiTietHoaDonThanhToans");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonTopping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChiTietHoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenTopping")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<Guid>("ToppingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HoaDonId" }, "IX_ChiTietHoaDonToppings_HoaDonId");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_ChiTietHoaDonToppings_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "ToppingId" }, "IX_ChiTietHoaDonToppings_ToppingId");

                    b.ToTable("ChiTietHoaDonToppings");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonVoucher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GiaTriApDung")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenVoucher")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_VoucherLogs");

                    b.HasIndex(new[] { "HoaDonId" }, "IX_VoucherLogs_HoaDonId");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_VoucherLogs_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "VoucherId" }, "IX_VoucherLogs_VoucherId");

                    b.ToTable("ChiTietHoaDonVouchers");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietTuyChinhMon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TuyChinhMonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_ChiTietTuyChinhMons_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "TuyChinhMonId" }, "IX_ChiTietTuyChinhMons_TuyChinhMonId");

                    b.ToTable("ChiTietTuyChinhMons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CongThuc", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SanPhamBienTheId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_CongThucs_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "SanPhamBienTheId" }, "IX_CongThucs_SanPhamBienTheId");

                    b.ToTable("CongThucs");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CongViecNoiBo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaHoanThanh")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCanhBao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayGio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("XNgayCanhBao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_CongViecNoiBos_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.ToTable("CongViecNoiBos");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BaoDon")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChiText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuShipper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayRa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayShip")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiShip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OldId")
                        .HasColumnType("int");

                    b.Property<string>("PhanLoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachHangText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("UuTien")
                        .HasColumnType("bit");

                    b.Property<Guid?>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_HoaDons_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "KhachHangId" }, "IX_HoaDons_KhachHangId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDonNhap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_HoaDonNhaps_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.ToTable("HoaDonNhaps");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DuocNhanVoucher")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OldId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_KhachHangs_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHangAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_ShippingAddresses");

                    b.HasIndex(new[] { "KhachHangId", "DiaChi" }, "IX_KhachHangAddresses_IdKhachHang_TenDiaChi")
                        .IsUnique();

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_KhachHangAddresses_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "KhachHangId" }, "IX_ShippingAddresses_KhachHangId");

                    b.ToTable("KhachHangAddresses");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHangGiaBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SanPhamBienTheId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("SanPhamBienTheId");

                    b.ToTable("KhachHangGiaBans");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHangPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("KhachHangID");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK_CustomerPhoneNumbers");

                    b.HasIndex(new[] { "KhachHangId" }, "IX_CustomerPhoneNumbers_KhachHangId");

                    b.HasIndex(new[] { "KhachHangId", "SoDienThoai" }, "IX_KhachHangPhones_IdKhachHang_SoDienThoai")
                        .IsUnique();

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_KhachHangPhones_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.ToTable("KhachHangPhones");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.LichSuNhapXuatKho", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdNguyenLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NguyenLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_LichSuNhapXuatKhos_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "NguyenLieuId" }, "IX_LichSuNhapXuatKhos_NguyenLieuId");

                    b.ToTable("LichSuNhapXuatKhos");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ip")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IP");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequestBodyShort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseBodyShort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Logs__3214EC07710A63D8");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_Logs_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.NguyenLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("OldId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TonKho")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_NguyenLieus_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.ToTable("NguyenLieus");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.NhomSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__NhomSanP__3214EC07C10A2B21");

                    b.HasIndex(new[] { "Ten" }, "IX_NhomSanPham_Ten")
                        .IsUnique();

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_NhomSanPhams_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.ToTable("NhomSanPhams");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_PaymentMethods");

                    b.HasIndex(new[] { "Ten" }, "IX_PaymentMethods_Ten")
                        .IsUnique();

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_PhuongThucThanhToans_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaBan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DinhLuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NgungBan")
                        .HasColumnType("bit");

                    b.Property<Guid?>("NhomSanPhamId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NhomSanPhamID");

                    b.Property<int>("OldId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TichDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VietTat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhomSanPhamId");

                    b.HasIndex(new[] { "Ten" }, "IX_SanPham_Ten")
                        .IsUnique();

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_SanPhams_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPhamBienThe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MacDinh")
                        .HasColumnType("bit");

                    b.Property<Guid>("SanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenBienThe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_SanPhamBienThes_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "SanPhamId" }, "IX_SanPhamBienThes_SanPhamId");

                    b.ToTable("SanPhamBienThes");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SuDungNguyenLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongThucId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCongThuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNguyenLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguyenLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CongThucId" }, "IX_SuDungNguyenLieus_CongThucId");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_SuDungNguyenLieus_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "NguyenLieuId" }, "IX_SuDungNguyenLieus_NguyenLieuId");

                    b.ToTable("SuDungNguyenLieus");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenHienThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaiTro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenDangNhap" }, "IX_TaiKhoan_TenDangNhap")
                        .IsUnique();

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_TaiKhoans_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Topping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NgungBan")
                        .HasColumnType("bit");

                    b.Property<int>("OldId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ten" }, "IX_Topping_Ten")
                        .IsUnique();

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_Toppings_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.ToTable("Toppings");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.TuyChinhMon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ChoPhepChonNhieuGiaTri")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_TuyChinhMons_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.ToTable("TuyChinhMons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DieuKienToiThieu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KieuGiam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OldId")
                        .HasColumnType("int");

                    b.Property<int?>("SoLanSuDungToiDa")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsDeleted", "LastModified" }, "IX_Vouchers_IsDeleted_LastModified")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "Ten" }, "IX_Vouchers_Ten")
                        .IsUnique();

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("ChiTieuHangNgay", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("ToppingNhomSanPhamLink", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.NhomSanPham", null)
                        .WithMany()
                        .HasForeignKey("NhomSanPhamId")
                        .IsRequired()
                        .HasConstraintName("FK_ToppingNhomSanPhamLinks_NhomSanPham");

                    b.HasOne("TraSuaApp.Domain.Entities.Topping", null)
                        .WithMany()
                        .HasForeignKey("ToppingId")
                        .IsRequired()
                        .HasConstraintName("FK_ToppingNhomSanPhamLinks_Topping");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonEntity", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.SanPhamBienThe", "SanPhamBienThe")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("SanPhamBienTheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamBienThe");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonNhapEntity", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDonNhap", "HoaDonNhap")
                        .WithMany("ChiTietHoaDonNhaps")
                        .HasForeignKey("HoaDonNhapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("ChiTietHoaDonNhaps")
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDonNhap");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonNo", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDonNos")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NoHoaDons_HoaDons_HoaDonId");

                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId");

                    b.Navigation("HoaDon");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonPoint", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDonPoints")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany("ChiTietHoaDonPoints")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CustomerPointLogs_KhachHangs_KhachHangId");

                    b.Navigation("HoaDon");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonThanhToan", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.ChiTietHoaDonNo", "ChiTietHoaDonNo")
                        .WithMany()
                        .HasForeignKey("ChiTietHoaDonNoId");

                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDonThanhToans")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payments_HoaDons_HoaDonId");

                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId");

                    b.HasOne("TraSuaApp.Domain.Entities.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("ChiTietHoaDonThanhToans")
                        .HasForeignKey("PhuongThucThanhToanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payments_PaymentMethods_PaymentMethodId");

                    b.Navigation("ChiTietHoaDonNo");

                    b.Navigation("HoaDon");

                    b.Navigation("KhachHang");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonTopping", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDonToppings")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.Topping", "Topping")
                        .WithMany("ChiTietHoaDonToppings")
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietHoaDonVoucher", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDonVouchers")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VoucherLogs_HoaDons_HoaDonId");

                    b.HasOne("TraSuaApp.Domain.Entities.Voucher", "Voucher")
                        .WithMany("ChiTietHoaDonVouchers")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VoucherLogs_Vouchers_VoucherId");

                    b.Navigation("HoaDon");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.ChiTietTuyChinhMon", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.TuyChinhMon", "TuyChinhMon")
                        .WithMany("ChiTietTuyChinhMons")
                        .HasForeignKey("TuyChinhMonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TuyChinhMon");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CongThuc", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.SanPhamBienThe", "SanPhamBienThe")
                        .WithMany("CongThucs")
                        .HasForeignKey("SanPhamBienTheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPhamBienThe");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDon", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangId");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHangAddress", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany("KhachHangAddresses")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KhachHangAddresses_KhachHangs_IdKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHangGiaBan", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.SanPhamBienThe", "SanPhamBienThe")
                        .WithMany()
                        .HasForeignKey("SanPhamBienTheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPhamBienThe");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHangPhone", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany("KhachHangPhones")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KhachHangPhones_KhachHangs_IdKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.LichSuNhapXuatKho", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("LichSuNhapXuatKhos")
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPham", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.NhomSanPham", "NhomSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("NhomSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_SanPhams_NhomSanPhams_NhomSanPhamId");

                    b.Navigation("NhomSanPham");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPhamBienThe", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.SanPham", "SanPham")
                        .WithMany("SanPhamBienThes")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SuDungNguyenLieu", b =>
                {
                    b.HasOne("TraSuaApp.Domain.Entities.CongThuc", "CongThuc")
                        .WithMany("SuDungNguyenLieus")
                        .HasForeignKey("CongThucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraSuaApp.Domain.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("SuDungNguyenLieus")
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongThuc");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.CongThuc", b =>
                {
                    b.Navigation("SuDungNguyenLieus");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDonNos");

                    b.Navigation("ChiTietHoaDonPoints");

                    b.Navigation("ChiTietHoaDonThanhToans");

                    b.Navigation("ChiTietHoaDonToppings");

                    b.Navigation("ChiTietHoaDonVouchers");

                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.HoaDonNhap", b =>
                {
                    b.Navigation("ChiTietHoaDonNhaps");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.KhachHang", b =>
                {
                    b.Navigation("ChiTietHoaDonPoints");

                    b.Navigation("HoaDons");

                    b.Navigation("KhachHangAddresses");

                    b.Navigation("KhachHangPhones");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.NguyenLieu", b =>
                {
                    b.Navigation("ChiTietHoaDonNhaps");

                    b.Navigation("LichSuNhapXuatKhos");

                    b.Navigation("SuDungNguyenLieus");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.NhomSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.PhuongThucThanhToan", b =>
                {
                    b.Navigation("ChiTietHoaDonThanhToans");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPham", b =>
                {
                    b.Navigation("SanPhamBienThes");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.SanPhamBienThe", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("CongThucs");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Topping", b =>
                {
                    b.Navigation("ChiTietHoaDonToppings");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.TuyChinhMon", b =>
                {
                    b.Navigation("ChiTietTuyChinhMons");
                });

            modelBuilder.Entity("TraSuaApp.Domain.Entities.Voucher", b =>
                {
                    b.Navigation("ChiTietHoaDonVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
